create table
  public.products (
    id bigint generated by default as identity,
    slug text not null,
    name text null,
    short_description text null,
    long_description text null,
    tags text[] null,
    price bigint null,
    constraint products_pkey primary key (id),
    constraint products_slug_key unique (slug)
  ) tablespace pg_default;